clear;
%function Hd = Butter_LP_example
%BUTTER_LP_EXAMPLE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 18-Apr-2025 12:26:52

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

Fpass = 0.1;         % Passband Frequency
Fstop = 0.2;         % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop);
Hd = design(h, 'butter', 'MatchExactly', match);

% filtering
n = 1:100;
x = cos(0.09*pi*n) + 2*cos(0.3*pi*n);

y = filter(Hd, x)

figure(1)
stem(n, x)
hold on
stem(n, y(1:length(n)))
hold off
% [EOF]
