function Hd = LeastSquares
%LEASTSQUARES Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 06-Apr-2025 12:56:09

% FIR least-squares Lowpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 8000;  % Sampling Frequency

N     = 30;    % Order
Fpass = 1000;  % Passband Frequency
Fstop = 1500;  % Stopband Frequency
Wpass = 1;     % Passband Weight
Wstop = 10;    % Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop]);
Hd = dfilt.dffir(b);

% [EOF]
