function Hd = LP_kaiser
%LP_KAISER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 26-Mar-2025 12:33:26

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 8000;  % Sampling Frequency

N    = 50;       % Order
Fc   = 700;      % Cutoff Frequency
flag = 'scale';  % Sampling Flag
Beta = 5;        % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
